# Generated by Django 2.2.6 on 2019-10-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellName', models.CharField(max_length=100)),
                ('cellAddress', models.CharField(max_length=150)),
                ('cellEmail', models.EmailField(max_length=254)),
                ('cellPhone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtName', models.CharField(max_length=50)),
                ('districtAddress', models.CharField(max_length=50)),
                ('districtPhone', models.IntegerField()),
                ('districtEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=150)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectorName', models.CharField(max_length=100)),
                ('sectorAddress', models.CharField(max_length=150)),
                ('sectorPhone', models.IntegerField()),
                ('sectorEmail', models.EmailField(max_length=254)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.District')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Province'),
        ),
    ]
