# Generated by Django 2.2.6 on 2019-10-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
                ('Type', models.CharField(max_length=250)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='Nid',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=10)),
                ('To', models.CharField(max_length=10)),
                ('Date', models.DateField(max_length=10)),
                ('Time', models.TimeField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('homeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homes.Home')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('termN0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homes.Term')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.IntegerField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('paymentMethod', models.CharField(max_length=200)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homes.Home')),
                ('transactionNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homes.Transaction')),
            ],
        ),
    ]
