# Generated by Django 2.2.6 on 2019-10-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0002_auto_20191007_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homes.Home'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='homeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homes.Home'),
        ),
    ]
